[package]
name = "logtool"
version = "0.2.4"
edition = "2024"

[[bin]]
name = "logtool"
path = "src/bin/cli.rs"

[[bin]]
name = "logtool-daemon"
path = "src/bin/daemon.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
